### ISSUE TITLE
Buttons don't work unless `no-update` file exists

### ISSUE THREAD

**Issue by NoozAbooz** [Botspot/cloudbuddy#1]
I tested this alot, and it seems like buttons don't do anything at all unless I make a blank `no-update` file

**Comment by Botspot** [comment]
Looks like the update procedure has been messed up somehow on your local system.
It's possible that `git pull` will fail, the commits will still mismatch, and the script will reload itself indefinitely. Each time the script is reloaded, it will check for updates again and the process repeats. That's my theory.

@mobilegmYT, when you run CloudBuddy in a terminal (and delete the `no-update` file of course), do you see any indication of repetitive `git pull`ing?

**Comment by NoozAbooz** [comment]
> Looks like the update procedure has been messed up somehow.
> It's possible that `git pull` will fail, the commits will still mismatch, and the script will reload itself indefinitely. Each time the script is reloaded, it will check for updates again and the process repeats. That's my theory.
> 
> @mobilegmYT, when you run CloudBuddy in a terminal (and delete the `no-update` file of course), do you see any indication of repetitive `git pull`ing?

I think while I was testing every commit branch, https://github.com/Botspot/cloudbuddy/commit/37104a8e244d8720219108535b5c521bf6097097 did have a repeating git pull but on newest commit with the file gone it doesn't output anything to terminal.

**Comment by Botspot** [comment]
I'm not sure what the problem is.
Right now I just made a change to the readme. This is a new commit, so cloudbuddy should auto-update once, and not again when I re-run `main.sh`.
It worked as intended:
```
pi@botspot:~ $ /home/pi/cloudbuddy/main.sh
CloudBuddy is out of date. Downloading new version...
To prevent update checking from now on, create a file at /home/pi/cloudbuddy/no-update
running 'git pull'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 15 (delta 9), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (15/15), done.
From https://github.com/Botspot/cloudbuddy
   e2fc08d..0bad3c3  main       -> origin/main
Updating e2fc08d..0bad3c3
Fast-forward
 README.md | 117 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--
 1 file changed, 115 insertions(+), 2 deletions(-)
git pull finished. Proceeding...
^C
pi@botspot:~ $ /home/pi/cloudbuddy/main.sh
pi@botspot:~ $ 
```
@mobilegmYT, what happens if you run one of CloudBuddy's subscripts?
```
~/cloudbuddy main.sh newdrive
```
Does any window appear? Any terminal output?

**Comment by NoozAbooz** [comment]
> I'm not sure what the problem is.
> Right now I just made a change to the readme. This is a new commit, so cloudbuddy should auto-update once, and not again when I re-run `main.sh`.
> It worked as intended:
> 
> ```
> pi@botspot:~ $ /home/pi/cloudbuddy/main.sh
> CloudBuddy is out of date. Downloading new version...
> To prevent update checking from now on, create a file at /home/pi/cloudbuddy/no-update
> running 'git pull'...
> remote: Enumerating objects: 17, done.
> remote: Counting objects: 100% (17/17), done.
> remote: Compressing objects: 100% (15/15), done.
> remote: Total 15 (delta 9), reused 0 (delta 0), pack-reused 0
> Unpacking objects: 100% (15/15), done.
> From https://github.com/Botspot/cloudbuddy
>    e2fc08d..0bad3c3  main       -> origin/main
> Updating e2fc08d..0bad3c3
> Fast-forward
>  README.md | 117 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--
>  1 file changed, 115 insertions(+), 2 deletions(-)
> git pull finished. Proceeding...
> ^C
> pi@botspot:~ $ /home/pi/cloudbuddy/main.sh
> pi@botspot:~ $ 
> ```
> 
> @mobilegmYT, what happens if you run one of CloudBuddy's subscripts?
> 
> ```
> ~/cloudbuddy main.sh newdrive
> ```
> 
> Does any window appear? Any terminal output?

I ran it again, it did git pull stuff and then the main script launched, yet the buttons still didn't work. Subscripts work fine though. I removed the part with the updater code so it is a issue with that stuff. Perhaps you could just make it git pull always on launch?

**Comment by Botspot** [comment]
> I ran it again, it did git pull stuff and then the main script launched, yet the buttons still didn't work.

What do you mean by "still didn't work"? Currently I'm imagining that when you run `main.sh`, nothing opens and nothing appears on-screen or in-terminal.

**Comment by NoozAbooz** [comment]
> > I ran it again, it did git pull stuff and then the main script launched, yet the buttons still didn't work.
> 
> What do you mean by "still didn't work"? Currently I'm imagining that when you run `main.sh`, nothing opens and nothing appears on-screen or in-terminal.

"Don't work" as in I press any button, and it clicks but nothing happens, the window doesn't close, new one doesn't open, etc. It just stays the same

**Comment by Botspot** [comment]
> "Don't work" as in I press any button, and it clicks but nothing happens, the window doesn't close, new one doesn't open, etc. It just stays the same

Wow. That's a completely different problem than the one I was picturing.

**Comment by Botspot** [comment]
And are you sure that creating the `no-update` file still fixes the problem?

**Comment by NoozAbooz** [comment]
> And are you sure that creating the `no-update` file still fixes the problem?

Yep. Same thing applies if I delete the section that updates and stuff in code

**Comment by Botspot** [comment]
> > And are you sure that creating the `no-update` file still fixes the problem?
> 
> Yep. Same thing applies if I delete the section that updates and stuff in code

Interesting. Obviously those buttons, when clicked, are successfully launching the scripts in the background. Perhaps it's an internet issue.- slow or buggy internet is holding up the `git ls-remote` command.
Try disconnecting your Pi completely from any internet connection and see if the problem persists.

**Comment by NoozAbooz** [comment]
> > > And are you sure that creating the `no-update` file still fixes the problem?
> > 
> > 
> > Yep. Same thing applies if I delete the section that updates and stuff in code
> 
> Interesting. Obviously those buttons, when clicked, are successfully launching the scripts in the background. Perhaps it's an internet issue.- slow or buggy internet is holding up the `git ls-remote` command.
> Try disconnecting your Pi completely from any internet connection and see if the problem persists.

I ran `git ls-remote https://github.com/Botspot/cloudbuddy/ HEAD` and it worked fine without any lag. I still suggest just running git pull always on startup and relaunching the script if there was a update.

**Comment by Botspot** [comment]
> I ran `git ls-remote https://github.com/Botspot/cloudbuddy/ HEAD` and it worked fine without any lag. I still suggest just running git pull always on startup and relaunching the script if there was a update.

Try disconnecting your Pi completely from any internet connection and see if the problem persists.

**Comment by NoozAbooz** [comment]
> Try disconnecting your Pi completely from any internet connection and see if the problem persists.

It didn't do anything for a few seconds, then the window popped up (the buttons still didn't do anything), and I got this in terminal
`fatal: unable to access 'https://github.com/Botspot/cloudbuddy/': Could not resolve host: github.com`

**Comment by Botspot** [comment]
> > Try disconnecting your Pi completely from any internet connection and see if the problem persists.
> 
> It didn't do anything for a few seconds, then the window popped up (the buttons still didn't do anything)

The terminal message is to be expected. If the buttons started working, we'd know that somehow the `git ls-remote` command was being a hindrance.
Try this adding this line in the update-checking code. It will display a pop-up with some information.
```
warning "Directory: $DIRECTORY\nlocalhash: $localhash\nlatesthash: $latesthash"
```
Screenshot for where the line should go in context:
![2021-07-30-201713_1366x768_scrot](https://user-images.githubusercontent.com/54716352/127724285-66f34c6a-2a1a-43ef-adb3-888bddd8e2b2.png)
If the pop-up does not appear after clicking a button, our problem is elsewhere entirely.

**Comment by NoozAbooz** [comment]
> > > Try disconnecting your Pi completely from any internet connection and see if the problem persists.
> > 
> > 
> > It didn't do anything for a few seconds, then the window popped up (the buttons still didn't do anything)
> 
> The terminal message is to be expected. If the buttons started working, we'd know that somehow the `git ls-remote` command was being a hindrance.
> Try this adding this line in the update-checking code. It will display a pop-up with some information.
> 
> ```
> warning "Directory: $DIRECTORY\nlocalhash: $localhash\nlatesthash: $latesthash"
> ```
> 
> Screenshot for where the line should go in context:
> ![2021-07-30-201713_1366x768_scrot](https://user-images.githubusercontent.com/54716352/127724285-66f34c6a-2a1a-43ef-adb3-888bddd8e2b2.png)
> If the pop-up does not appear after clicking a button, our problem is elsewhere entirely.

I did further testing, it's broken because of `cd "$HOME"` in line 124 for some reason.

**Comment by Botspot** [comment]
> I did further testing, it's broken because of `cd "$HOME"` in line 124 for some reason.

That is exceedingly strange. Try launching a `warning` pop-up that displays the contents of the $HOME variable.

**Comment by NoozAbooz** [comment]
I have no idea what that means

**Comment by Botspot** [comment]
> > That is exceedingly strange. Try launching a warning pop-up that displays the contents of the $HOME variable.
> 
> I have no idea what that means

Add a line anywhere before the `cd $HOME` that says this:
`warning "HOME: $HOME"`
We're basically using my `warning` function as a makeshift `echo` command for situations when we don't think you'd see `echo`'s output.

**Comment by NoozAbooz** [comment]
> > > That is exceedingly strange. Try launching a warning pop-up that displays the contents of the $HOME variable.
> > 
> > 
> > I have no idea what that means
> 
> Add a line anywhere before the `cd $HOME` that says this:
> `warning "HOME: $HOME"`
> We're basically using my `warning` function as a makeshift `echo` command for situations when we don't think you'd see `echo`'s output.

![image](https://user-images.githubusercontent.com/44128563/127724851-20964def-c420-4b85-89d3-3e9762363712.png)
Looks fine

**Comment by Botspot** [comment]
> Looks fine

I'm not sure what else to suggest. In order to `git pull`, we have to be `cd`'ed into the CloudBuddy directory. Removing that is not an option.
CD'ing back to $HOME is technically optional I guess, but I'd rather cd back to the default location before proceeding, for consistency.
Maybe try quoting the cd command?
```
cd "$HOME"
```
And try this:
```
cd ~/
```

**Comment by NoozAbooz** [comment]
I got it working by storing current directory before cding into a variable via pwd and then cding into it after the update.

**Comment by Botspot** [comment]
> I got it working by storing current directory before cding into a variable via pwd and then cding into it after the update.

Did the two tips I suggested above ***not*** work?

**Comment by NoozAbooz** [comment]
> > I got it working by storing current directory before cding into a variable via pwd and then cding into it after the update.
> 
> Did the two tips I suggested above _**not**_ work?

They didnt

**Comment by Botspot** [comment]
> They didnt

Very strange. Did you happen to have anything weird going on with `sudo`?
In any case, I've pushed today's worth of updates, including your recommendation.
