### ISSUE TITLE
Issue using File Manager

### ISSUE THREAD

**Issue by Yekrut1000** [Botspot/cloudbuddy#11]
Issue: I can't access mounted drive through File Manager, but can access through terminal with sudo prefaced commands.

Setup: Raspberry Pi400 running with Raspberry OS (bullseye, 64 bit).  Using CloudBuddy, I mount my OneDrive repository to the empty directory 'cloud' (/home/pi400/cloud).

Before mounting, the directory's permissions are:
```
    drwxrwxrwx 2 pi400 pi400 4096 Jul 19 08:41 cloud
```
After mounting, the directory's permissions change to:
```
    d????????? ? ?     ?        ?            ? cloud
```
As stated, File Manager can no longer access the directory after OneDrive is mounted (the mount does appear in left hand top panel), however I can browse/delete/create the mounted OneDrive directories and files by using terminal commands, prefaced by sudo.  Without sudo, I receive the standard:
    ls: cannot access 'cloud': Permission denied

Using 'sudo chmod u+rwx cloud' has no effect while OneDrive is mounted to the directory cloud.
This may not be an issue if I have missed something in setting up CloudBuddy?  However I believe I have followed all the steps.

**Comment by Botspot** [comment]
Thank you for reaching out. I hope we can resolve this issue you are having.

On Bullseye 64-bit, I just mounted my OneDrive to ~/cloud to try to reproduce the problem you reported. However, on my system, everything worked fine. The mount appeared in the file manager, and I was able to browse my files normally using the file manager and `ls`, all without sudo.

Please run this command and paste the output here:
```
rclone version
```

**Comment by Yekrut1000** [comment]
Hi, Thanks for the reply.  Here is the result:
pi400@raspberrypi:~ $ rclone --version
rclone v1.63.1
- os/version: raspbian 11.7 (64 bit)
- os/kernel: 6.1.21-v8+ (aarch64)
- os/type: linux
- os/arch: arm (ARMv7 compatible)
- go/version: go1.20.6
- go/linking: static
- go/tags: none

I tried CloudBuddy immediately after turning the Pi400 on, same result.  If FileManager is set to the empty folder 'cloud' as CloudBuddy mounts the OneDrive to it, FiileManager immediately reponds with "The specified directory '/home/pi400/cloud' is not valid".  Upon un-mounting OneDrive, the folder in FileManager can be accessed again.

I also tried newly created empty directories at different locations, same result.

I will try a complete removal of cloudbuddy and a re-install.
Thanks

**Comment by Botspot** [comment]
Cloudbuddy is just a fancy script that uses the `rclone` command in the background. Reinstalling CloudBuddy should not have any effect.

Your output from running `rclone --config` is more or less identical to mine, though I notice that rclone reports your `os/arch` to be armv7. Are you sure your OS is 64-bit? The OS can still be 32-bit even if you switched to the 64-bit kernel.

It is possible that the problem is how rclone mounts folders, using a different fusemount tool. I am not sure how it does it, but I think it is flexible in that way, so that could be what is going on here.
Please run this command: `apt search --names-only fuse` and send me the output.

**Comment by Yekrut1000** [comment]
Output from 'apt search --names-only fuse' command in attached text file, link at bottom.
I'm pretty sure everything is 64 bit - I used the raspberry imager on my pc to download and install the 64 bit OS+desktop onto a new sdc card. Details from site:
Raspberry Pi OS with desktop
Release date: May 3rd 2023
System: 64-bit
Kernel version: 6.1
Debian version: 11 (bullseye)
Size: 818MB
Show SHA256 file integrity hash:
[Release notes](https://downloads.raspberrypi.org/raspios_arm64/release_notes.txt)

My complete"re-install" of cloudbuddy involved removing rclone first, and deleting the cloudbuddy directory before re-cloning cloudbuddy and running '~/cloudbuddy/main.sh'.

However, now I have more information on issue:
a) immediately running cloudbuddy from same terminal session as I used to install it, worked as it should, i.e., FileManager correctly displayed  my OneDrive contents, and the terminal displayed the various commands as I mounted and un-mounted OneDrive through the cloudbuddy interface.
b) Closing that terminal and opening new terminal, and executing main.sh worked the same, i.e., FileManager correctly displayed OneDrive contents.
c) At end of each terminal session I did unmount OneDrive, and terminated the cloudbuddy app.
d) However, trying to run cloudbuddy from the installed menu link in the main menu (Internet/CloudBuddy), produced the same effect as before - the empty folder 'cloud' I mounted OneDrive to was no longer accessable via FileManager, but the cloudbuddy interface still mounted and unmounted OneDrive to the empty directory. sudo ls commands in a terminal did display the one drive contents, while FileManager could not
e) For now I'll open a terminal and run  '~/cloudbuddy/main.sh' to use cloudbuddy

Seems weird though.  Sometime later, I'll try constructing my own destop link, and shell script, to run cloudbuddy and see how it goes.
Thanks again

[output.txt](https://github.com/Botspot/cloudbuddy/files/12115459/output.txt)

**Comment by Botspot** [comment]
Your findings are very intriguing to me. I've not had this issue and it works for me on PiOS Bullseye 64-bit to run CloudBuddy from the main menu.

Some time I would like to remote into your system using TeamViewer to see for myself what is wrong. What time would be convenient for you?

**Comment by Yekrut1000** [comment]
So I did write my own desktop file, and as you might expect it is very simple:

        [Desktop Entry]
        Exec=/home/pi400/cloudbuddy/main.sh
        Icon=/home/pi400/cloudbuddy/icons/cloud.png
        Type=Application
        Categories=Applications
        Name[en_AU]=CloudBuddy
        StartupNotify=false

The intriguing thing is that it worked, that is, after mounting OneDrive via the cloudbuddy session started by this desktop file, FileManager correctly displayed the one drive contents.  After that, I added a main menu link back into where the original was, and its command simply pointed again to main.sh: /home/pi400/cloudbuddy/main.sh

This also worked as it should, so I think I am good to go.  I still have no idea why the original installations produced the effect they did, possibly some weird thing that is set on my machine, especially if no-one else ever raises the same issue with you.  So thanks for you help, and quick responses. Much appreciated.

**Comment by Botspot** [comment]
Did you place that desktop file in your main menu (`~/.local/share/applications`), or did you run it from the file manager?

**Comment by Yekrut1000** [comment]
Initially I had put it in my desktop directory: ~/home/pi400/Desktop
But upon receiving you question I cut it out of there, and pasted it into  ~/.local/share/applications.  Still works as it should.  I have now left it in that folder, but also put a copy back onto/into the desktop folder.  Either works.

Cheers

**Comment by Botspot** [comment]
The only main difference I can spot between your desktop file and the original is StartupNotify.
```
$ cat /home/pi/.local/share/applications/cloudbuddy.desktop
[Desktop Entry]
Name=CloudBuddy
Comment=The ultimate cloud storage manager.
Exec=/home/pi/cloudbuddy/main.sh
Icon=/home/pi/cloudbuddy/icons/cloud-square.png
Terminal=false
Type=Application
Categories=Application;Network;RemoteAccess;
StartupNotify=true
```
I cannot imagine that causing any difference, but if you could experiment with that, it would be helpful.

> I still have no idea why the original installations produced the effect they did, possibly some weird thing that is set on my machine, especially if no-one else ever raises the same issue with you. So thanks for you help, and quick responses. Much appreciated.

No, you might be onto something. As the creator of [Pi-Apps](https://github.com/Botspot/pi-apps), I have been shocked with the number of times something was completely broken, and despite a strong userbase, it sometimes took _over a month_ for anyone to actually let me know there was a problem. (Not sure if everyone assumed it was their fault, or if it is laziness, or if my userbase is much smaller than what the numbers say, or if nobody thinks to let the developer know, or if everybody thinks the developers already know and don't care)

I have long wondered why CloudBuddy has not gained much popularity. It has been moderately successful but I expected 100 times as much. Less than 50 people downloaded CloudBuddy this week, but Pi-Apps was downloaded 9000 times this week.
So it is entirely possible that your issue is a factor into why CloudBuddy never really became popular.

**Comment by Botspot** [comment]
For that matter, try transitioning your .desktop file to the original one, by changing one line at a time. After every change, try to see if the problem came back. This should narrow it down.

**Comment by Yekrut1000** [comment]
Lol - I started transiting as you suggest before your last comment! :-)

So I moved from my CloudBuddy.desktop file posted above towards your version, one line/change at a time.  After each edit I then:
          saved desktop  file
          started cloudbuddy through edited desktop link
          mounted one drive
          started filemanager and checked I could view one drive directories
          exited filemanager
          unmounted one drive
          exited clouudbuddy
          next edit.

Unfortunately, I now have:         
          
          [Desktop Entry]
          Name=CloudBuddy
          Comment=The ultimate cloud storage manager.
          Exec=/home/pi400/cloudbuddy/main.sh
          Icon=/home/pi400/cloudbuddy/icons/cloud-square.png
          Terminal=false
          Type=Application
          Categories=Applications;Network;RemoteAccess;
          StartupNotify=true

and it still works!!!!!!  So things are still no clearer as to what was occurring.  Maybe you should post a question on the PiApps site asking if down-loaders ran into an (or this) issue with cloudbuddy?

Any other suggestions you want me to try?  I think the only thing still different n the desktop file is my raspberry directory is pi400 and yours is pi.
I'm going to exit all apps, reboot and see if it all still works after these edits.  stay tuned.

**Comment by Yekrut1000** [comment]
Rebooted - all still working as it should.
Note I have not changed anything with the original files.  Simply deleted the main menu entry and desktop link, and wrote my own desktop file (now identical with original), and put in a new main menu item.  (which simply points to main.sh)
but they both now "work".

Another piece of info: when I did have the problem, if I tried to run "ls" in a terminal on the mount folder (after mounting one drive), without the sudo prefix, the system simply went away and never came back. pushing return/enter key or using control-C returned  the normal cursor to the terminal 
Cheers

**Comment by Botspot** [comment]
I cannot think of anything else to try. Let me know if it happens again.

**Comment by Yekrut1000** [comment]
Hi,

I have been thinking more about this issue overnight, and since it is now closed, I thought I would respond via email.   One earlier symptom of "ls -l" returning ???? etc. for file permissions after mounting onedrive, is systematic of FUSE doing something weird with permissions for the user during the mounting process. There are a number of reports of such behaviour.  I don't know exactly what it does do to mess up, but I tried to think about what was different between the first install (where filemanager didn't work with the mounted onedrive) and the second install (where it worked) I did of CloudBuddy. (Where filemanager worked by running main.sh from the same terminal session used to install.)

All I can say is I definitely removed rclone before running the second install (using sudo rm -r  /usr/bin/rclone); and I'm pretty sure I did not do that for the first install, even though you do suggest it.   Reason being that everything should have been up to date, since I had just done an update/upgrade session!

Anyway, my suggestion is you might consider updating main.sh to definitely remove rclone, and re-install it from source.  If you do, you probably should state that in the instructions. Hope that helps.

Another piece of info: I renamed my cloudbuddy desktop file, then restored the original one from the first install from the trash.  Guess what? It works, so I do think the issue is basically a rclone/FUSE issue.

Regards,

Steve (Yekrut1000)

> 
> On ,Sat Jul 22 2023 00:48:46 GMT+0930 (Australian Central Standard Time),

**Comment by Botspot** [comment]
I have improved CloudBuddy in the way you suggest. It now installs the ARM 64-bit version of rclone if your OS is 64-bit, and it ensures that rclone is the latest version, overwriting the current rclone version if necessary.
These changes can be reviewed at commit https://github.com/Botspot/cloudbuddy/commit/38098029456626742925e218ced57b477d3fc247.
