### ISSUE TITLE
GoogleDrive issue

### ISSUE THREAD

**Issue by Yekrut1000** [Botspot/cloudbuddy#12]
Hi,

So while OneDrive works a treat, I am having little luck with connecting to my GoogleDrive.  Using the CloudBuddy gui, I can name a new cloud drive (MyGoogleDrive), but when I click on the GoogleDrive button, all that happens is the gui retracts to a single 'cancel' button, and it stays there.  No rclone driven browser window opens to allow me to enter my login details for google drive.

So if I push the 'cancel' button, the gui returns.  If I now look at listed drives in the gui "MyGoogleDrive" appears in the list - so I removed it so that I could try a more basic approach.  On my second attempt, I opened a terminal and ran the 'main.sh' script so I could monitor the commands being executed.  The gui popped up as usual and I went through the motions again.  It still halted at the same place, with no browser window opening, and only a 'cancel' button showing.  I have copied the terminal output into the attached file. It stops on an entry requiring a 'service_account_file'. No default value is given, and the line above says 'Press enter to leave empty'.  So I did that in the terminal (after a few minutes), but the whole script terminates and I am back at the terminal cursor.  I have added some comments into the terminal transcript, detailing what I did at those points.  Those few entries are surrounded by [ ].

All suggestions appreciated.  Note that through the standard Chromium window I can log in, and navigate, my actual GoogleDrive.

[GoogleDrive_terminal.txt](https://github.com/Botspot/cloudbuddy/files/12157661/GoogleDrive_terminal.txt)

**Comment by Botspot** [comment]
CloudBuddy runs the rclone program in the background, and it literally types inputs to rclone to navigate its terminal interface. If the rclone interface changes, or if a new version of rclone asks a new question that it did not used to ask, then my implementation breaks.

Today I will try to research how feasible it is to use rclone directly to prevent this from happening again. For now you have to wait. If you really need it to work now, you can run `sudo apt install --reinstall rclone` and before running cloudbuddy you can modify the main.sh script to not overwrite the installed rclone with the latest version.

**Comment by Yekrut1000** [comment]
Hi, Thanks for the response, but I took a different approach for now.  What I did was run 'rclone config' in a terminal, to step through the process with mounting Google Drive, then modified the gdrive.exp file (after saving current version), commenting out the questions rclone no longer asks  (e.g., it no longer asks about using  auto config).

I ran CloudBuddy with the edited gdrive.exp, and it worked well (at least this time, that is).  I have appended the updated gdrive.exp if you want to use it - but please verify it works!

I hope you are successful with using rclone directly. Also, are you thinking of adding more cloud storage sites to CloudBuddy?
Thanks again.
[gdrive.exp.edited26-7-2023.txt](https://github.com/Botspot/cloudbuddy/files/12167127/gdrive.exp.edited26-7-2023.txt)

**Comment by Botspot** [comment]
I have improved the main.sh script to directly use rclone to create the drive. Cloudbuddy no longer requires the `expect` command, and I have deleted the .exp files from this github repository.
This should make it immune to future interface changes on rclone's end.

@Yekrut1000, I only added buttons for Google Drive, Dropbox, and OneDrive because AFAIK they are the top 3 most widely used cloud storage platforms. If you would like to suggest a specific one I should look into adding, go ahead and suggest it!

**Comment by Yekrut1000** [comment]
Absolutely agree with those three as top 3.  Unfortunately, I already have 3 other devices attached to my free dropbox, which is their limit for free accounts.  Next main storage one for me would be Box, but I can always go to rclone directly to mount it if I need to. (Now that I have played with rclone)
I'll update cloudbuddy now - thanks again for the rapid work.
