### ISSUE TITLE
Breaks after fail to unmount drive

### ISSUE THREAD

**Issue by NoozAbooz** [Botspot/cloudbuddy#3]
![image](https://user-images.githubusercontent.com/44128563/127725940-c1c1ed88-7a39-436d-b29b-1031de92433f.png)

I keep forgetting to cd out of the folder before unmount, perhaps implement a warning if a unmount fails with a already in use error?

**Comment by Botspot** [comment]
> I keep forgetting to cd out of the folder before unmount, perhaps implement a warning if a unmount fails with a already in use error?

Are you asking for the unmount button to detect if the mountpoint is busy, before it attempts to unmount it? I doubt that's possible with a fuse mount...

**Comment by NoozAbooz** [comment]
> > I keep forgetting to cd out of the folder before unmount, perhaps implement a warning if a unmount fails with a already in use error?
> 
> Are you asking for the unmount button to detect if the mountpoint is busy, before it attempts to unmount it? I doubt that's possible with a fuse mount...

Also when I unmount it and it shows the error, cloudbuddy doesn't return to home screen. At least you can probably add that in right?

**Comment by Botspot** [comment]
> > > I keep forgetting to cd out of the folder before unmount, perhaps implement a warning if a unmount fails with a already in use error?
> > 
> > 
> > Are you asking for the unmount button to detect if the mountpoint is busy, before it attempts to unmount it? I doubt that's possible with a fuse mount...
> 
> Also when I unmount it and it shows the error, cloudbuddy doesn't return to home screen. At least you can probably add that in right?

With a new function, yes. I've just fixed this with commit d26c233be7abed99c20d95ece449f8735f297d63.
