### ISSUE TITLE
Pi-Apps

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/cloudbuddy#4]
More of a suggestion than an issue, will you add this to pi-apps?

**Comment by Botspot** [comment]
I will add CloudBuddy to Pi-Apps when I'm reasonably sure CloudBuddy is bug-free and stable. Currently I've received record little feedback for CloudBuddy, so for the time being, I'm waiting to see how it's received by the community.

**Comment by Pythonic456** [comment]
Ok, I might actually use it next Monday when I use my Pi again.
