### ISSUE TITLE
Remote upload possible

### ISSUE THREAD

**Issue by rajeshsahoo12** [Botspot/cloudbuddy#5]
Let us assume below scenario :-

I have multiple static download links with me saved in notepad file which are media in nature. Is the remote upload directly from url to onedrive is possible...?

Url can be in placed inside notepad file or pasted in batch. Whichever is possible.

**Comment by Botspot** [comment]
If I understand your question correctly, it sounds like you want to import files straight into your OneDrive, without having to first download them and then upload them.

While this is probably possible using the versatile functionality of `rclone`, I don't know how to do it. Perhaps you would find the help you need by asking on [the rclone forums](https://forum.rclone.org/)?
