### ISSUE TITLE
How to start at boot?

### ISSUE THREAD

**Issue by Maki2007** [Botspot/cloudbuddy#8]
I know, this is not an issue.
But it is a nice tool and easy to use.
But is there a way to start it automatic at boot?
Thanks

**Comment by Itai-Nelken** [comment]
[autostar](https://github.com/Botspot/autostar) (another useful tool by botspot) makes it really simple to do that.

**Comment by Botspot** [comment]
> I know, this is not an issue.

That's not a problem! Github Issues are commonly used to ask questions or to make suggestions as well. Thanks for reaching out, by the way. :)

> But it is a nice tool and easy to use.

Thanks! I like Cloudbuddy too and I use it often. But compared to WoR-Flasher or Pi-Apps it has never really become widely popular. If you have any idea as to why, please let me know. By the way, how did you find out about Cloudbuddy?

> But is there a way to start it automatic at boot? Thanks

Cloudbuddy is a front-end for `rclone`. If you want a particular action to happen on boot, it may be best to check what `rclone` command cloudbuddy actually uses to complete that action. Once you know the direct rclone command, you could paste it into something that would run commands on boot. As recommended by Itai, Autostar is a great choice for this.

If you really want the Cloudbuddy *user-interface* to appear on boot, then add an autostart entry and have it run `~/cloudbuddy/main.sh`

If this answers your question, @Maki2007, feel free to close the issue. Have a great day!

**Comment by Maki2007** [comment]
I always like getting answer from you - You answer is good and detailed. 
I have maybe a idea why CloudBuddy didn’t become popular: Such automatic sync-to-the-cloud programs are often used on main pc or school laptops. There are some data there is important to have the opportunity to access every and in every device. But on a Raspberry Pi you don’t have need to access your files

**Comment by Maki2007** [comment]
I always like getting answer from you - You answer is good and detailed. 
I have maybe a idea why CloudBuddy didn’t become popular: Such automatic sync-to-the-cloud programs are often used on main pc or school laptops. There are some data there is important to have the opportunity to access every and in every device. But on a Raspberry Pi you don’t have the need to access your files every where and on every device, because it is some files you maybe only can “use” on the Pi and you don’t do productive stuff like word or excel on a raspberry pi. 

How I found it? I was visiting pi-apps and saw the “ad” banner at the top with cloudbuddy. I was using the browser to download files from my OneDrive and the browser experience on a pi isn’t always the best and fastest experience. 

I want it to automatically attached OneDrive to the file system. So how do I find the actual rclone command? By running ~/cloudbuddy/main.sh and check the terminal output?

**Comment by Maki2007** [comment]
And about https://github.com/Botspot/wor-flasher/issues/72, I found a way to run W10 in a VM on the Raspberry Pi. It runs slow on a SSD, but its work, if you still are interested.

**Comment by Botspot** [comment]
> I always like getting answer from you - You answer is good and detailed. I have maybe a idea why CloudBuddy didn’t become popular: Such automatic sync-to-the-cloud programs are often used on main pc or school laptops. There are some data there is important to have the opportunity to access every and in every device. But on a Raspberry Pi you don’t have the need to access your files every where and on every device, because it is some files you maybe only can “use” on the Pi and you don’t do productive stuff like word or excel on a raspberry pi.

Interesting theory. I personally use my Pi for everything, and I hope others try it with the help of Pi-Apps, but I understand that I am in a small minority.

> I want it to automatically attached OneDrive to the file system. So how do I find the actual rclone command? By running ~/cloudbuddy/main.sh and check the terminal output?

Exactly. You will want to look for output like this:
```
Mount drive
Choosing drive...
Choosing mountpoint...
To get here from the command line, run this:
/home/pi/cloudbuddy/main.sh mountdrive "Onedrive" "/home/pi/Web drives/Onedrive"
Running this command: rclone mount "Onedrive:" "/home/pi/Web drives/Onedrive"
```

> And about https://github.com/Botspot/wor-flasher/issues/72, I found a way to run W10 in a VM on the Raspberry Pi. It runs slow on a SSD, but its work, if you still are interested.

Yes I still am interested. Please post your findings in that issue.
