### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by vrobot-2** [Botspot/cloudbuddy#9]
Botspot if you would have any expireince on windows, maybe you could deploy it to windows or a web interface. That would be amazing. BTW, I love all the projects you worked on. Especially Pi-apps.

**Comment by Botspot** [comment]
Hello Virat, CloudBuddy is a shell script. It is written in bash (Bourne-Again SHell) specifically. This scripting language is only compatible with Linux.

However, `rclone` itself, which is what Cloudbuddy actually uses under the hood, does run on Windows. Also, rclone has a web interface.

**Comment by vrobot-2** [comment]
thank you for confirming, I just saw that.
